### ISSUE TITLE
Enlightenment, EFL and Tizen

### ISSUE THREAD

**Issue by ajwillia-ms** [techmeetup/edinburgh#104]
A potential talk topic to catch folk up on where the Enlightenment community.

Most folk have not heard much in 12 years or so. that was back in E16 days. We're now at E21 - there is a whole new library stack that is also powering the Tizen platform available on many IoT and mobile devices.

I could take the chance also to talk about the IDE that I'm building and some new bootstrap scripts that make it really easy to get all our latest work :)

**Comment by marksutherland** [comment]
Hi @ajwillia-ms ! Thanks for volunteering to speak. It's been a long time since I've used enlightenment, but I still have a soft spot for Eterm in particular. 

Would you be interested in talking in October (12th)? If not, there's space in November or December as well.

Thanks again!

**Comment by ajwillia-ms** [comment]
Hi,

Unfortunately October is very busy but November should be fine - that would be the 9th right?

**Comment by marksutherland** [comment]
Yeah, November would be the 9th. Consider yourself booked!

**Comment by ajwillia-ms** [comment]
Cool - can we title it "Enlightenment: Life after 0.16"? Do you need a summary at some point too?

**Comment by marksutherland** [comment]
Sure, sounds good to me. We usually don't publish anything more than the
title, so don't worry about the summary.

Thanks!

Mark

**Comment by marksutherland** [comment]
Hi @ajwillia-ms , just confirming you're still good to talk on Wednesday. If you have slides it would be great if you can send me a copy by Tuesday as a backup. There's micro displayport and HDMI inputs available so you can present from your own laptop if you want, otherwise there's a PC hooked up to the AV system. There should be a youtube live stream on the night which will stay up afterwards, let me know if that's a problem. At the moment it looks like you might be the only speaker, so there shouldn't be a rush.

Let me know if you have any questions or concerns and I'll see what I can do! Otherwise, see you on Wednesday!

**Comment by ajwillia-ms** [comment]
Hi Mark,

Yeah all still good. Getting the slides to you by Tuesday might be tight
but I will do what I can.
I might take you up on the use of a laptop as I think my adapter is packed
away somewhere to move house.

See you Wednesday,
Andrew

**Comment by ajwillia-ms** [comment]
Hi Mark,

Here is the presentation for tomorrow - will this play OK?
I would like to use a laptop that's set up for the projector if that's
possible.

https://github.com/ajwillia-ms/presentations/raw/master/Enlightenment/life_beyond_16/life_beyond_16.pdf

Thanks and see you tomorrow,
Andrew

**Comment by marksutherland** [comment]
Thanks @ajwillia-ms !
