### ISSUE TITLE
Martin Asenov

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#123]
I plan to do a talk in machine learning. Interested in both the January lighting talks and a longer talk as well. GitHub account: @masenov

**Comment by marksutherland** [comment]
Hi @masenov , are you happy to do a lightning talk next Wednesday (11th) or would you prefer a longer talk later in the year? Thanks for volunteering!

**Comment by masenov** [comment]
Hi @marksutherland I am sorry for the delay in replying. I am more interested to do a longer talk. March will be a good time for me, if it's not full already. Thank you!

**Comment by marksutherland** [comment]
Hi @masenov , March still has space, so I can book you in for that! I'll get in touch with further details closer to then, but in the mean time do you have a title for your talk? Thanks!

**Comment by masenov** [comment]
Hi @marksutherland yes please book me a place for then. The title of my talk will be "Gaussian Processes: Theory and applications". I am coming to the meeting next week, so we can have a chat :)

**Comment by marksutherland** [comment]
Ok, that sounds great! Look forward to chatting this week :)

**Comment by masenov** [comment]
Hi Mark, am I still in line for giving a talk next week?

**Comment by marksutherland** [comment]
Hi Martin, yes, you're still lined up, as long as that still suits you.

There's hdmi and micro display port available if you want to present yourself, otherwise there's a PC hooked up to the AV system and I'll probably take my laptop with me as well just in case. Either way, it would be a good idea to email me a copy of your slides by Tuesday to act as a backup.

There is a live stream, so if you'd rather the talk not be recorded, let me know and I'll pass it on. 

I think you're familiar with how things usually go, so if you have any questions let me know and I'll see what I can do.
