### ISSUE TITLE
talk on writing CVs and other recruitment tips

### ISSUE THREAD

**Issue by MariusCiocanel** [techmeetup/edinburgh#134]
Ruaridh Miller and Calvin Blyth from Head Resourcing offered to do a talk about mistakes they see when people send them CV (form a recruiter perspective). They're also happy to answer any questions people might have about how recruiting works and approaches to finding jobs.

**Comment by MariusCiocanel** [comment]
I mentioned they (or one of them) could do a talk in the July Techmeetup.

**Comment by marksutherland** [comment]
Any idea if they're going to take up that offer?

**Comment by CalvinBlyth** [comment]
Hi Mark,

Myself and Ruaridh would be delighted to take that opportunity to assist your attendees.

**Comment by MariusCiocanel** [comment]
I have a few questions you could answer during the talk:
- what technologies have been seen a rise in demand in the last 6-12 months?
- what are the technologies that make up the majority of the roles that clients are trying to fill? Java? C#?
- advice about doing salary research as a candidate. What should people who are trying to enter the tech industry expect in terms of salaries (ranges) ?

I'll add more questions as I think of them.

**Comment by CalvinBlyth** [comment]
Can I just confirm that we are still invited to speak at your Event next week?

**Comment by marksutherland** [comment]
Hi Calvin,

Yes, you are still invited! Do you have a title for your talk?

We have HDMI and micro display port available if you want to present from
your own laptop, otherwise there is a PC available we can present from. The
event is livestreamed to youtube and kept up for posterity, let us know if
that's a problem and we can pause the stream during your talk.

Folk usually start arriving from 6.30pm and enjoy the free beer and pizza
until the introductions around 7.30pm. First talk will start just before
8pm, last for 20-25mins with some questions, then a short break before the
second. We usually finish around 9pm and head to the pub. I gather you came
along last month and probably know all that already though :)

Let me know if you have any questions or concerns!
