### ISSUE TITLE
Peter Aitken: Potential Speaker

### ISSUE THREAD

**Issue by JiggyPete** [techmeetup/edinburgh#140]
Hi Folks, 

If possible I'd like to share my talk **"How can our language and behaviour be more inclusive?"** with the local tech community in September

### Talk Description

Our words and actions can have a deep and profound effect on people in the community and within our teams. So much so that they step back from participating in events or even leave their place of work.

Even those of us who think ourselves as considerate can sometimes be doing things that inadvertently causes problems.

In this talk we will cover a number of real-world scenarios which aim to put attendees in the shoes of those who receive unwanted and inappropriate language and/or behaviour.

Today, what can we do to be more inclusive?

### Notes

Each attendee is unique and the aim is to invoke empathy by putting them in scenarios which include sexism, harassment and mental health (with references to suicide). Ideally this will make attendees more aware of, and improve, their own language and behaviour.

**Comment by MariusCiocanel** [comment]
making this one of the talks for the September. @JiggyPete please let us know if your availability changes before then

**Comment by JiggyPete** [comment]
This sounds great @MariusCiocanel. I'll have a laptop with a few slides. Is there anything else I need to know about the event?

**Comment by marksutherland** [comment]
Hi @JiggyPete 

Just confirming you're up for speaking in September (13th). I'm assuming you may not have been to a tech meetup before, so I'll give you a run down of how the night goes (if you have, I'm sure this will be familiar).

Folk usually start arriving from about 6.30pm at Skyscanner's office, where there's free drinks and pizza and a chance to catch up and gossip. Around 7.30pm we do a round of introductions, where everyone says who they are and why they've come along. Then there's a short break and the first talk will start before 8pm. Talks are usually about 20-25mins with some time for questions. After another short break we have the second talk, then we should be finished around 9pm, at which point we head to the pub.

Skyscanner have a pretty good AV set up, so if you want to project from your own laptop there is HDMI and micro display port inputs, otherwise there is a PC there we can use instead. There's usually a live stream that we keep up for posterity, so let us know if you'd rather it wasn't recorded and I'll pass it on. You can find previous streams here: https://www.youtube.com/channel/UCWMSLoZh4U4Pgc8n8ylw8Pg . 

I think that's most of the main points. Let me know if you have any concerns or questions and I'll see what I can do. Thanks for offering to speak!

**Comment by JiggyPete** [comment]
Hi @marksutherland,

It's been a long time since I've been through to Tech Meetup Edinburgh. Maybe 4 years.

All of that sounds great. 

More than happy for the talk to be recorded, and it will probably be a bit longer than 25 mins :-)

The one important thing to mention is that there will be a number of content warnings. (harassment and suicide)
Might make it easier for attendees who'd like to excuse themselves, if I speak second. That way people can more discretely leave during half time.

Looking forward to coming along and meet folks and thank you for running the event!
Peter

**Comment by marksutherland** [comment]
That sounds good to me. Do you know roughly how long you think it'll be? We can start the talks a bit earlier and shorten the breaks to account for it.

I dunno if you're aware, but we have a code of conduct that you might find interesting: https://github.com/techmeetup/edinburgh/blob/master/CodeOfConduct.md . We occassionally have to remind folk that it exists, but thankfully nobody has run seriously afoul of it. I know we have a few regulars that will appreciate the content warnings, and a few that will likely find a talk like this quite helpful.

Anyway, looking forward to it! Let me know if you have any concerns or queries!

**Comment by marksutherland** [comment]
cc: @alistairhann

**Comment by JiggyPete** [comment]
@marksutherland I'd guess nearer the 40 minute mark, currently.

It's great that there is a CoC in place. 
Extra points to have it prominently display on the website and reminders at each meetup.

**Comment by JiggyPete** [comment]
That's fine with me @marksutherland, talk is about 30-40 mins at the minute. 
Look forward to seeing you and the team on Wednesday!
