### ISSUE TITLE
How to win at anything ever (maybe): how AIs learn to play games

### ISSUE THREAD

**Issue by pbsinclair42** [techmeetup/edinburgh#147]
I mentioned to @marksutherland at a recent TechMeetup that I might be interested in talking about some of the recent work in AI development, in particular MCTS and the success it's had with Go, among other games.  Do you think this could be an interesting topic?

**Comment by marksutherland** [comment]
Hi @pbsinclair42 ! Sorry I didn't respond sooner, busy time of the year.

That sounds like a great topic to me :) As it happens, we don't have anyone scheduled in January at the moment, so if you fancy speaking on the 10th we have space for you. Otherwise we have room in February and March (both the 14th weirdly).

Thanks for volunteering!

**Comment by pbsinclair42** [comment]
I'm not able to make it to the January meetup I'm afraid, but February or March could work for me, aye, let me know which would suit you better!

**Comment by marksutherland** [comment]
Hi @pbsinclair42 , is February still good for you? Thanks!

**Comment by pbsinclair42** [comment]
Aye, that'll be fine!  Roughly how long should I aim to talk for?

**Comment by marksutherland** [comment]
About 20-25 mins with 5 mins of questions, but we can move things about a little if necessary. Is the title of the issue still the title for your talk?

There is mini display port and hdmi adapters available if you want to present from your own laptop, otherwise there is a PC we can download the slides to. There is usually a live stream which will be kept up on youtube for posterity, let us know if you'd rather your talk wasn't recorded.

Let me know if you have any questions!
