### ISSUE TITLE
Presentation Proposal—Taming a massive testsuite: rationalising code coverage with Hadoop MapReduce

### ISSUE THREAD

**Issue by 08009004** [techmeetup/edinburgh#150]
My name is Pierre, I work as a Software Engineering Intern at Analog Devices (Edinburgh office), under @kilbswhitecrow (who has done Tech Meet-Up talks in the past).  I would like to propose a presentation for the February meet-up.

Validation of our biggest product—a compiler toolchain—is achieved with test suites that have grown organically for almost 20 years and we suspect that many tests execute only a small part of the source code, again and again, providing little confidence increase, while other parts are rarely exercised if at all.  This is automated across 20 to 30 machines, full-time, for two months and failures further cost many man-hours to investigate.

Previous attempts to identify an optimal subset of tests failed because of the vast amount of data to analyse.  MapReduce parallel runtime frameworks offer a new angle to look at this kind of problem and I have been working on a piece of software to perform data-intensive cloud processing and identify a sufficient, minimal set of compiler validation test cases.

**Comment by marksutherland** [comment]
Hi @08009004 !

Thanks for offering to talk! This sounds really interesting. We have space in February and maybe March (both on the 14th of the month). Will Analog Devices be ok for you to talk about the content you're covering publicly? We normally have a live stream, but we can disable it for the talk if we need to.

Thanks for volunteering!

**Comment by kilbswhitecrow** [comment]
Hi Mark. Yep, Analog Devices is fine with this presentation being public/streamed - there's no IP or confidential info exposed in the presentation.

**Comment by 08009004** [comment]
Hi Mark, I can do February then

**Comment by marksutherland** [comment]
That's great to hear!

In case you haven't been along to TMU before here's how things usually run:

Folk start arriving from 6.30pm, there's free drink and pizza and a chance for everyone to catch up and gossip. About 7.30pm we do a round of introductions were everyone says who they are and why they've come along. There's then a short break and the first talk will start somewhere between 7.45 and 8pm. Talks are usually about 20-25mins with 5 mins of questions. We then have another short break, the second talk, and usually finish up at 9pm and head to the pub.

There are mini display port and HDMI adapters available if you want to present from your own laptop, otherwise there is a PC we can download your slides to. I've already mentioned the live stream.

Let me know if you have any questions or concerns and I'll see what I can do. Thanks for volunteering again!

**Comment by 08009004** [comment]
Hi Mark, thanks for inviting me :)
I think I will just put powerpoint slides together and bring them on my USB flash drive, have you had any problems with that in the past?

**Comment by marksutherland** [comment]
Hi Pierre,

Sorry I didn't get back sooner, we had our second child a few weeks ago and I've been a bit distracted :)

While it's a good idea to take the slides on a USB stick, it would also be useful to have them on dropbox or elsewhere on the internet as I'm not sure there's easy USB access to the PC hooked up to the AV system.

I'm going to use the issue topic as the title of your talk, unless you want to use something else.

Finally, I've realised I don't know what your surname is! Please let me know ASAP so I can use it in the announcement email.

Let me know if you have any other questions!

**Comment by 08009004** [comment]
Congratulations :-)
I could actually bring a laptop with HDMI outlet if it's any easier?  Title of talk is "Taming a massive testsuite: rationalising code coverage with Hadoop MapReduce" indeed, and surname is Ruiz.
