### ISSUE TITLE
Anna Donohoe - TBC

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#36]
@spatzkatz said she'd speak about something related to coming into tech from humanites, NLP and/or UX.

**Comment by marksutherland** [comment]
Hi @spatzkatz, are you still interested in giving a talk? We're looking for another speaker for July 8th if you're available.

**Comment by marksutherland** [comment]
Hi @spatzkatz, can you see these comments? I'm afraid I don't have another way to contact you.
If you can, would you be interested in speaking at TMU in October (14th) or maybe November (11th)?

**Comment by evilneuro** [comment]
Does this help? https://www.linkedin.com/in/hapax

**Comment by spatzkatz** [comment]
Hello everyone,

Apologies, I have been very busy since the end of my degree. I just moved
from Edinburgh to the US and started a full-time job, so I'm afraid I won't
be able to help. Thanks for keeping me in mind though, I appreciate it! I
hope to come back to Edinburgh again one day.

All the best,
Anna


On Fri, Sep 25, 2015 at 12:11 PM, William Anderson <notifications@github.com

**Comment by marksutherland** [comment]
Hi Anna,

Congrats on the job! Hope it's going well, and thanks for volunteering! Best of luck,

Mark
