### ISSUE TITLE
Christos Matskas - Getting started with cloud development using Azure

### ISSUE THREAD

**Issue by mikemcquaid** [techmeetup/edinburgh#45]
@cmatskas and I chatted over email.

**Comment by mikemcquaid** [comment]
@cmatskas How does June 10th look for you to do this? Thanks!

**Comment by cmatskas** [comment]
Hi @mikemcquaid, the 10th sounds a bit tight. Could we potentially push it to July?

**Comment by mikemcquaid** [comment]
@cmatskas Yup, that should be fine, thanks.

**Comment by cmatskas** [comment]
Hi @mikemcquaid, that's really helpful. Are we approaching this from a dev perspective or a DevOps one?

**Comment by mikemcquaid** [comment]
@cmatskas Either works!

**Comment by cmatskas** [comment]
How long is the talk for and is there a specific area I should be focusing? There's tons I can talk about so I would like to tailor it as much as possible to the audience. If this is for me to decide, I would probably talk about web apps, storage, AD, Mobile services, all accompanied by demos. All this can squeeze comfortably in 1 hour and from there we can tailor it down or up depending on what's needed

**Comment by MariusCiocanel** [comment]
I'd aim for 25 minutes for the talk and 5 minutes for questions from the audience

**Comment by cmatskas** [comment]
25mins? Wow, that's gonna be compressed!

**Comment by marksutherland** [comment]
Hi @cmatskas, are you still up for talking in July? Date would be the 8th.

**Comment by cmatskas** [comment]
Hi Mark,


Yes, we are still good for July and the 8th should be fine


Let me know if you need anything else


Thanks,

CM






Sent from Windows Mail





From: Mark
Sent: ‎Tuesday‎, ‎23‎ ‎June‎ ‎2015 ‎21‎:‎09
To: techmeetup/edinburgh
Cc: chris@towzietyke.co.uk





Hi @cmatskas, are you still up for talking in July? Date would be the 8th.

**Comment by marksutherland** [comment]
On 23 June 2015 at 23:58, Christos Matskas <notifications@github.com> wrote:

> Hi Mark,
>
>
> Yes, we are still good for July and the 8th should be fine
>
>
> Let me know if you need anything else
>
>
Hi Christos,

Thanks for confirming! Looking forward to it :)

Mark

**Comment by cmatskas** [comment]
Hello folks,

I hope you are well. Are we still on track for Wednesday?

Is there anything on your website or Lanyrd to advertise the event? Could we get something online to generate some traction? Could you also send me all the details for the event etc so that I can get organised? Is it OK if I record my session for personal use? If you could provide anything else you think necessary, then I would be really grateful

Thanks!

**Comment by marksutherland** [comment]
Hi Christos,

Everything looks good at our end. We've announced the talks on our mailing list and on twitter as we usually do, and should have the website updated soon. I've also notified the Slack group. Feel free to spread the links below further.

We usually record talks as long as presenters are happy about it, and I think we're going to be streaming live to YouTube this month  (@MariusCiocanel can maybe confirm). 

If there's anything else you need please let us know, otherwise we'll see you on Wednesday at 6.30pm!

Mailing List:
https://groups.google.com/d/msg/techmeetup/3l0fL6Ywbt4/HLZAtomINwMJ
Twitter:
https://twitter.com/techmeetup/status/618143328387751936

**Comment by marksutherland** [comment]
Talked on the 8th July, offered to talk again in the future. Can someone close this?
