### ISSUE TITLE
Gavin Montague: Email infrastructure & deliverability.

### ISSUE THREAD

**Issue by Govan** [techmeetup/edinburgh#91]
I'd be happy to give a heavily updated version of my talk on how to run an email service for your webapp

https://speakerdeck.com/leftbrained/the-minimum-you-should-know-about-email-as-a-developer

I've given versions of it twice and only one person actively disliked it, so I'm counting that as a win.

**Comment by marksutherland** [comment]
Hi @Govan , how soon do you think you could give this talk? Would next Wednesday (13th) be possible? We're in a bit of an odd situation where we have lots of speakers available next month, but nobody confirmed for this month yet. If not, would June (8th) or July (13th) suit you better? Thanks for volunteering!

**Comment by Govan** [comment]
@marksutherland, yep, next week would be doable.

**Comment by marksutherland** [comment]
Excellent, thank you very much!

I'm guessing you've probably been before and know how things go, but it's worth going over how the evening runs to make things clear. Folk usually start arriving at Skyscanner's offices from 6.30pm, and there's time for free beer, pizza and catching up. About 7.30pm we do a round of introductions, where everyone gets a chance to say who they are and why they've come along. After that, there's a short break then the first talk. Talks are usually about 20-25 mins with time for questions. After the first talk, there's another break, then the second talk, and then we usually head off to the pub afterwards.

There's mini display port and HDMI adapters available if you want to present slides from your laptop, otherwise I should be there with my laptop. Either way, it's best to send a copy of your slides by Tuesday night as a backup (mark AT the-sutherlands.co.uk).

I think that's all the main things. Please let me know if you have any questions!

Once again, thanks for volunteering to talk, especially at such short notice!

**Comment by MariusCiocanel** [comment]
🚢 d! Thanks!

**Comment by MariusCiocanel** [comment]
A link to the talk since I had to look it up to share it with someone :) https://youtu.be/FZFugty_5ng?t=4745
